frappe/wiki

wiki/wiki/workspace/wiki/wiki.json
Adding workspace to access from the desktop
**Preview:**
=> Adding workspace

wiki/public/js/edit_asset.js, wiki/public/js/edit_wiki.js, wiki/public/scss/contributions.bundle.scss, wiki/public/scss/contributions.scss, wiki/public/scss/edit_wiki.scss, wiki/public/scss/wiki.scss, wiki/wiki/doctype/wiki_page/templates/breadcrumbs.html, wiki/wiki/doctype/wiki_page/templates/comment.html, wiki/wiki/doctype/wiki_page/templates/edit.html, wiki/wiki/doctype/wiki_page/templates/navbar_items.html, wiki/wiki/doctype/wiki_page/templates/web_sidebar.html, wiki/wiki/doctype/wiki_page/wiki_page.py, wiki/www/contributions.html
=> Fix  styles

wiki/patches.txt, wiki/wiki/doctype/wiki_page/templates/show.html, wiki/wiki/doctype/wiki_page_revision/patches/add_usernames.py, wiki/wiki/doctype/wiki_page_revision/wiki_page_revision.json, wiki/www/compare.html, wiki/www/revisions.html, wiki/www/revisions.py
=> feat(minor): show username instead of `name` email

.gitignore, requirements.txt, wiki/public/js/edit_asset.js, wiki/public/scss/edit_wiki.scss, wiki/wiki/doctype/wiki_page/templates/edit.html, wiki/wiki/doctype/wiki_page/wiki_page.py, wiki/wiki/doctype/wiki_page_patch/wiki_page_patch.json, wiki/www/drafts.html, wiki/www/drafts.py, wiki/www/edit.py
Ability to save contribution as draft
=> feat: Draft mode

wiki/wiki/doctype/wiki_page/wiki_page.py, wiki/wiki/doctype/wiki_settings/wiki_settings.json
Search is currently controlled by website settings
added a setting in wiki settings to control it for wiki
closes #49
=> feat: search as a first class feature

wiki/public/scss/wiki.scss
=> style: remove broken links styles

wiki/wiki/doctype/wiki_page/wiki_page.py
If the cache is not invalidated the sidebar shows stale data
=> fix: invalidate cache on route edit

wiki/wiki/doctype/wiki_page/wiki_page.py, wiki/wiki/doctype/wiki_sidebar/wiki_sidebar.py
` frappe.get_doc('Wiki Sidebar', side_bar_name).clone(string_to_replace, replace_with)`
would create a clone of the wiki sidebar with wiki pages
=> feat: add support for cloning via console

wiki/public/js/edit_asset.js
https://user-images.githubusercontent.com/9079960/154471459-f0acac1b-705e-4886-8ca9-81a332790b2b.mov
=> fix: popover not hiding automatically

wiki/patches.txt, wiki/wiki/doctype/wiki_page/templates/show.html, wiki/wiki/doctype/wiki_page_revision/patches/add_usernames.py, wiki/wiki/doctype/wiki_page_revision/wiki_page_revision.json, wiki/www/compare.html, wiki/www/revisions.html, wiki/www/revisions.py
https://github.com/frappe/wiki/pull/46
=> [Backport version-13] feat(minor): show username instead of name email

wiki/public/js/render_wiki.js
=> fix: hide nav buttons when item is not found

wiki/public/js/edit_asset.js
auto-generate a default caption from filename while adding images.
=> feat: auto generate caption from filename

wiki/wiki/doctype/wiki_page_patch/wiki_page_patch.json, wiki/wiki/doctype/wiki_page_revision/wiki_page_revision.json
Changed field type of message field from Data to Text, because it is a text field on the user end.
=> fix: Changed fieldtype of message field from Data to Text

.github/workflows/ci.yml, wiki/wiki/doctype/wiki_page/test_wiki_page.py
=> ci: add test workflow

wiki/public/scss/wiki.scss, wiki/wiki/doctype/wiki_page/test_wiki_page.py, wiki/www/compare.html, wiki/www/compare.py
=> feat: revert wiki to a point in revision history

wiki/wiki/doctype/wiki_page_patch/wiki_page_patch.json
throw error "data too long for column 'diff' at row 1" while too many changes
=> update diff fieldtype from Text to Long Text

wiki/public/js/edit_wiki.js, wiki/public/scss/edit_wiki.scss, wiki/public/scss/wiki.scss, wiki/wiki/doctype/wiki_sidebar/wiki_sidebar.py
fix #112 
<details><summary>Old Version</summary>
<p>
</p>
</details>
<details><summary>New Version</summary>
<p>
</p>
</details>
<details><summary>Final Version</summary>
<p>
</p>
</details>
=> feat: delete sidebar group

wiki/public/js/edit_wiki.js, wiki/public/js/wiki.js, wiki/public/scss/wiki.scss
=> style: wiki sidebar ui revamp

wiki/public/js/edit_asset.js, wiki/public/js/edit_wiki.js, wiki/public/js/render_wiki.js, wiki/public/js/wiki.js, wiki/public/scss/contributions.scss, wiki/public/scss/edit_wiki.scss, wiki/public/scss/wiki.scss, wiki/wiki/doctype/wiki_page/templates/navbar_items.html, wiki/wiki/doctype/wiki_page/templates/wiki_doc.html, wiki/wiki/doctype/wiki_page/templates/wiki_navbar.html, wiki/wiki/doctype/wiki_page/wiki_page.py, wiki/wiki/doctype/wiki_settings/wiki_settings.json
closes #42 
<details><summary>Screenshots</summary>
<p>
</p>
</details>
=> feat: dark mode

.pre-commit-config.yaml
Reverts black update in 06723ca.
=> ci: fix black errror

wiki/wiki/doctype/migrate_to_wiki/migrate_to_wiki.py, wiki/wiki/doctype/wiki_page/wiki_page.py
Becomes necessary with https://github.com/frappe/frappe/pull/22143
=> fix: import path for file utils

wiki/public/scss/wiki.scss
=> style: avatar dropdown alignment

wiki/public/js/render_wiki.js, wiki/public/js/wiki.js, wiki/public/scss/edit_wiki.scss, wiki/public/scss/wiki.scss, wiki/wiki/doctype/wiki_page/templates/navbar_search.html, wiki/wiki/doctype/wiki_page/templates/show.html, wiki/wiki/doctype/wiki_page/templates/web_sidebar.html, wiki/wiki/doctype/wiki_page/templates/wiki_doc.html, wiki/wiki/doctype/wiki_page/templates/wiki_navbar.html, wiki/wiki/doctype/wiki_page/wiki_page.py, wiki/wiki/doctype/wiki_page_patch/wiki_page_patch.js, wiki/wiki/doctype/wiki_page_patch/wiki_page_patch.py
=> style: more espresso design changes

wiki/wiki/doctype/wiki_page/wiki_page.py, wiki/wiki/doctype/wiki_space/wiki_space.js, wiki/wiki/doctype/wiki_space/wiki_space.json
=> feat(wiki-space): space specific logo and navbar settings

wiki/public/js/render_wiki.js, wiki/public/scss/wiki.scss, wiki/wiki/doctype/wiki_group_item/wiki_group_item.json, wiki/wiki/doctype/wiki_page/templates/page_settings.html, wiki/wiki/doctype/wiki_page/templates/show.html, wiki/wiki/doctype/wiki_page/wiki_page.py
=> feat(wiki-page): page settings

wiki/wiki/doctype/wiki_page/templates/show.html
Fix
```
{ { script } }
```
to
```
{{ script }}
```
=> Fix custom script

cypress/e2e/wiki.cy.js, cypress/e2e/wiki_sidebar.cy.js, package-lock.json, package.json, wiki/public/js/render_wiki.js, wiki/public/scss/edit_wiki.scss, wiki/public/scss/wiki.scss, wiki/wiki/doctype/wiki_feedback/patches/delete_wiki_feedback_item.py, wiki/wiki/doctype/wiki_feedback/wiki_feedback.py, wiki/wiki/doctype/wiki_page/templates/navbar_items.html, wiki/wiki/doctype/wiki_page/templates/show.html, wiki/wiki/doctype/wiki_page/templates/wiki_navbar.html, wiki/wiki/doctype/wiki_page/wiki_page.py, wiki/wiki/doctype/wiki_settings/wiki_settings.json, yarn.lock
1. Fixed cache issue on wiki pages.
2. Removed theme toggle and picked theme directly from OS.
3. Removed the edit menu beside the title and added it beside the modified time.
4. Changed font sizes.
=> fix: cache, animation and menu

wiki/public/js/render_wiki.js, wiki/public/js/wiki.js, wiki/public/scss/wiki.scss
Fixed sidebar scroll animation
=> fix: sidebar animation

wiki/public/js/render_wiki.js
Show dark mode logo in dark mode
=> fix: dark mode logos

wiki/public/js/wiki.js, wiki/wiki/doctype/wiki_page/wiki_page.py
=> fix: section heading links

wiki/public/scss/edit_wiki.scss
=> fix: table styling

wiki/public/js/editor.js, wiki/wiki/doctype/wiki_page/wiki_page.py
This ensures Wiki page draft content is displayed correctly.
=> fix: display draft and contributions content

wiki/public/scss/edit_wiki.scss, wiki/public/scss/wiki.scss, wiki/wiki/doctype/wiki_page/templates/editor.html
- Fixed buttons, dropdown menu css styles
- Fixed title input field where the title would move on focus
=> fix: css styling

wiki/public/scss/edit_wiki.scss, wiki/public/scss/wiki.scss
=> fix: fix heading and numbered list styles

wiki/public/js/render_wiki.js
=> feat: show confirmation modal before discarding changes

wiki/wiki/doctype/wiki_page/templates/base.html
=> perf: toggle dark mode before content loads

wiki/wiki/doctype/wiki_page/wiki_page.py
closes: https://github.com/frappe/wiki/issues/361
=> fix: clear cache on page update

wiki/public/js/editor.js
=> fix: empty spaces added to title

wiki/public/js/wiki.js, wiki/wiki/doctype/wiki_page/templates/show.html, wiki/wiki/doctype/wiki_page/wiki_page.py
=> fix: footer navigation buttons & page toc alignment

.github/helper/install.sh, wiki/hooks.py, wiki/public/js/render_wiki.js, wiki/public/scss/modal.scss, wiki/wiki/doctype/wiki_page/search.py, wiki/wiki/doctype/wiki_page/sqlite_search.py, wiki/wiki/doctype/wiki_page/wiki_page.py, wiki/wiki/doctype/wiki_settings/wiki_settings.json, wiki/wiki/doctype/wiki_space/wiki_space.py, wiki/wiki_search.py
i needed a playground (in prod) for some search ideas i need for another project i'm working on. search is based on SQLite FTS5 cause it serves as a decent stepping board. added some minor reranking over returned results.
baseline has better (anecdotal) results compared to existing (redis based) search. added minor ux improvements (reduced debounce).
=> feat: sqlite fts based search

wiki/wiki/doctype/wiki_page/sqlite_search.py
- use query_only pragma
- us ro mode
=> fix: use readonly for sqlite on search

wiki/search.py, wiki/wiki/doctype/wiki_page/sqlite_search.py
group title based matches together, i.e. title matches are given higher precedence over content matches
=> fix: tweak search heuristics

wiki/public/js/wiki.js
Before - on mobile screen sidebar titles are not opening properly
https://github.com/user-attachments/assets/3c0d2e90-6e28-4583-ab06-02df885e03e5
After -  Now on click its toggling
https://github.com/user-attachments/assets/78e97254-d49b-4b6b-b7f0-6bb9a7df90fe
closes #416
=> fix: sidebar toggle on small screen
