- wiki/wiki/doctype/wiki_page/wiki_page.py
reroute to original page breaks when the patch was not submitted
> fix: reroute to original page breaks

- wiki/patches.txt
- wiki/public/js/edit_asset.js
- wiki/wiki/doctype/wiki_page/wiki_page.json
- wiki/wiki/doctype/wiki_page/wiki_page.py
- wiki/wiki/doctype/wiki_sidebar/wiki_sidebar.py
- wiki/wiki/doctype/wiki_sidebar_item/patches/fetch_route.py
- wiki/wiki/doctype/wiki_sidebar_item/wiki_sidebar_item.json
- wiki/www/compare.py
- wiki/www/edit.py
- wiki/www/new.py
- wiki/www/revisions.py
A route was not allowed to be edited from the desk because it was linked with a name. 
Names are random now. 
Routes can be edited from desk
> feat: editable route from desk

- wiki/patches.txt
- wiki/wiki/doctype/wiki_page/wiki_page.py
- wiki/wiki/doctype/wiki_page_revision/wiki_page_revision.json
- wiki/wiki/doctype/wiki_page_revision_item/wiki_page_revision_item.json
- wiki/wiki/doctype/wiki_page_revision_item/wiki_page_revision_item.py
- wiki/wiki/doctype/wiki_sidebar_item/patches/wiki_page_revision_item_table.py
- wiki/www/revisions.py
Wiki Page Revision will have a list of links that will point to the wiki pages
This was done to ensure saving space when the revision history of two pages are same
> refactor(Wiki Page Revision): wiki pages in table

- wiki/wiki/doctype/wiki_page/templates/show.html
Broken links checked considers `/left` and `/right` link placeholders to be broken replacing them with `#`
> fix: use semantic left right link placeholders

- wiki/wiki/doctype/wiki_page/wiki_page.py
> fix: Pass wiki page name as filter instead of route

- wiki/hooks.py
- wiki/wiki/doctype/wiki_page/templates/show.html
**Issue:** Wiki routes `/<wiki-page>/new` & `/<wiki-page>/edit` is conflicting with webform routes `<web-form>/new` & `<web-form>/edit`.
changing the wiki route to `/<wiki-page>/new-wiki` & `/<wiki-page>/edit-wiki`
> fix: Wiki /new and /edit route conflicting with webform routes

- wiki/www/contributions.html
- wiki/www/contributions.py
- wiki/www/drafts.html
- wiki/www/drafts.py
1. #93 changed some paths from `/new` / `/edit` to `/new-wiki` / `/edit-wiki`, but some paths were remaining which are causing 404 errors
https://user-images.githubusercontent.com/32034600/184419063-c611c065-519e-4a5a-a8d0-6a8924cf002e.mov
#
2. After https://github.com/frappe/wiki/pull/87, Contributions page (`/contributions`) is **still** erroring out due to "Draft" not being present in the `color_map` - as it only changed the filters in `get_drafts`/`get_contributions` but didn't to change the same in the `get_context` function(s)
Visit: www.frappeframework.com/contributions
#
Other Changes:
- moved out common functionality in `contributions.py` to a separate function
- moved out common functionality in `drafts.py` to a separate function
- removed `color_map` from drafts.py & harcoded …
> fix: Misc fixes

- wiki/wiki/doctype/wiki_page/wiki_page.json
- wiki/wiki/doctype/wiki_page/wiki_page.py
This PR adds the following meta tags in every Wiki page:
1. Description
2. Keywords
3. Image
4. Image width and height defaults to 1200 by 630px - this is needed for Facebook Open Graph
Hopefully doing this will now allow us to find documentation from Google by improving page rankings. 
I wasn't able to figure out how to add these fields in the web page editor. Maybe someone can help me with that.
#97 should be partially done with this.
> feat: add meta tags for Wiki Page

- wiki/public/js/edit_asset.js
- wiki/wiki/doctype/wiki_page/templates/edit.html
- wiki/www/edit.py
Wiki uses file uploader and file uploader is written in vue2 up to frappe version 14 and in version 15(develop) it is re-written in vue 3. This PR allows support for both the vue2 & vue 3 versions.
> fix: fileUploader breaking because of vue3

- wiki/public/scss/wiki.scss
The Table of Contents on the right side wasn't scrollable - hence defeating the purpose if there were too many sections on a page.
**Before**
The right sidebar wasn't scrollable.
**After**
The right sidebar is scrollable. 
The height of the `ul` is set to `100vh - 300px` - I just based it off on browser dimensions. No need to make this responsive since it's hidden on tablets/mobile anyway.
> fix: table of content is scrollable

- wiki/wiki/doctype/wiki_page/templates/show.html
- wiki/wiki/doctype/wiki_page/test_wiki_page.py
- wiki/wiki/doctype/wiki_page/wiki_page.py
closes #41 
We now have a Delete Page option along with Edit Page and New Page
> feat: delete wiki page

- wiki/wiki/doctype/wiki_page/templates/show.html
When printing a wiki page, hide the following elements which don't make sense in this context:
- Edit button
- Last edited (shown as timedelta from the time of access, becomes meaningless pretty fast)
- Next/Previous page buttons
> fix: hide elements in print

- wiki/hooks.py
- wiki/wiki/doctype/wiki_page/search.py
fix #161
The `rebuild_index_if_not_exists` seems to be corrupting whatever indices we had.
> fix: rebuild index if not found while search

- package.json
- wiki/public/js/editor.js
- wiki/public/scss/edit_wiki.scss
- wiki/public/scss/wiki.scss
- yarn.lock
> feat: add support for tiptap task-item

- wiki/public/scss/wiki.scss
In the hopes of fixing #196
I only added `width: 100%` to CSS selector `.sidebar-item :first-child` to expand the child `<a>` element.
This make the sidebar links consistent with the sidebar groups which are full-width as well as making it easier to navigate through the pages without having to think how long the title is.
I left the `margin-right: auto`, but by making the `width: 100%`, it removes the margin. There may be a situation where it is needed, but it seems very unlikely.
> feature: Make sidebar items' links full-width

- wiki/wiki/doctype/wiki_page/search.py
On v14, redis 3.x is being used which doesn't have inbuilt redisearch package which was added in redis 4.x. 
There's no way both of them can be supported. This way at least wiki stays usable in old version with old style website search.
> fix: Fallback to old style search when redisearch isn't available

- wiki/wiki/doctype/wiki_page_patch/wiki_page_patch.py
This PR addresses issue #244 (refer to the full description there).
New Wiki Pages can be published in two distinct ways: (i) immediately, if the creator holds the `Wiki Approver` role; or (ii) pending manual approval of the associated `Wiki Page Patch` if the creator lacks the `Wiki Approver` role.
The logic for this is embedded in the whitelisted `update` function within the `wiki/doctype/wiki_report/wiki_report.py` file. This function checks if the user possesses the `submit` perm for that doctype to determine whether to submit it immediately or not. There is an issue within this function: it expects to receive the `new_sidebar_items` argument from the API call, and subsequently stores it (at runtime) in the `Wiki Page Patch` object. However, this doctype lacks a corresponding field, …
> fix: add new pages to sidebar after patch approval

- wiki/public/scss/wiki.scss
Currently, the padding on the `<li>` element makes some of the highlighted area not a link that redirects you to a page. By transferring the padding to the `<a>` element, the whole highlighted area is a clickable link.
Perhaps it would even be better to transfer the `:hover` styles from the `.sidebar-group-item` to the `.sidebar-item a` to avoid confusion.
> style: Make whole sidebar link clickable

- wiki/wiki/doctype/wiki_page/wiki_page.py
> fix: display private pages for logged in users

- wiki/wiki/doctype/wiki_feedback/wiki_feedback.py
- wiki/wiki/doctype/wiki_settings/wiki_settings.json
- Implement rate limiting for feedback submissions to prevent spamming
- Hourly limit can be configured via Wiki Settings
> feat(wiki): add rate limiting for feedback submissions

- wiki/wiki/report/wiki_broken_links/test_broken_link_checker.py
- wiki/wiki/report/wiki_broken_links/wiki_broken_links.js
- wiki/wiki/report/wiki_broken_links/wiki_broken_links.py
- feat: handle internal links
- refactor: break down into smaller functions
- fix(ux): better copy
> feat: broken links report enhancements

- .github/helper/install_dependencies.sh
- wiki/public/build.json
- wiki/wiki/workspace/wiki/wiki.json
> chore: cleanup

- wiki/wiki/doctype/wiki_page/wiki_page.py
- wiki/wiki/doctype/wiki_page/wiki_renderer.py
- perf: don't fetch web view doctypes for no reason
- perf: evaluate wiki space redirects later
- perf: re-enable page cache
> perf: speed up wiki page rendering

- wiki/public/js/wiki.js
closes: https://github.com/frappe/wiki/issues/363
> fix: editor not using name of page loaded without page reload

- wiki/wiki/doctype/wiki_page/wiki_page.py
Adjusted conditional to bypass the logged in user guest restriction. This is to fix issue [#360](https://github.com/frappe/wiki/issues/360).
> fix: Logged in users not bypassing newly added guest restrictions.

- wiki/public/js/wiki.js
fixes #387
the sidebar, instead of performing a full refresh of the page, swaps the main content, and thus leaving the title (the <title> tag) of the document unchanged, this is fixed by manually updating the title.
https://github.com/user-attachments/assets/cf26ba53-8a47-4d42-920d-b33dce18f918
> fix: update page title in the DOM when loading wiki content using sidebar

- wiki/public/js/wiki.js
fixes #389 by manually adding the "rotate" class to the active sidebar-group icon on initial load.
https://github.com/user-attachments/assets/a557da4d-f7bc-4d6d-9eae-aedc91a3227a
> fix: manually set the rotation of the active sidebar-group icon

- wiki/public/js/render_wiki.js
- wiki/public/js/wiki.js
This PR resolves the issue where clicks on sidebar nav items were not recognised on iPad. The solution involves adding a `touchstart` listener. PFA video.
Changes Made:
- Added a `touchstart` listener at 2 places (sidebar group and sidebar item)
- Minor renaming of class attribute (`draggable` -> `non-draggable`) since those elements were filtered out from Sortable when not in edit mode. 
This issue significantly affected the usability of all Frappe app wikis, including popular applications like ERPNext, Frappe HR, and others. On iPads, users were unable to interact with the sidebar properly. PFA video. Also, below are raised issues,
- #182 
- #216 
https://github.com/user-attachments/assets/d26b1e80-fd9b-45c6-9e64-c7b26f9eda17
https://github.com/user-attachments/assets/f5016697-1e88-47eb- …
>  Fix iPad Sidebar Click Issue

- wiki/public/scss/markdown.scss
- wiki/public/scss/navbar.scss
- wiki/wiki/doctype/wiki_page/templates/show.html
- wiki/wiki/doctype/wiki_page/wiki_page.py
This PR addresses multiple UI issues related to the navbar and wiki dropdown on smaller devices:
- Fixes menu jittering on mobile devices caused by explicit `height` CSS property which also hides the main content in its vicinity.
- Resolves dropdown overflow: Ensures that the `wiki-options` dropdown no longer causes horizontal overflow or layout breaking on smaller viewports.
- Hides wiki-options for guest users: Since guest users do not have permissions to edit or manage pages, the options are now conditionally hidden from them to reduce clutter and prevent confusion.
- For menu jittering
- Remove explicit height causing menu jitter on collapse
- For wiki-options dropdown overflow
- Add `overflow-x` to wiki-navbar-container to ensure dropdown adjusts within screen boundaries
- Add check …
> fix: Navbar menu jitter , wiki-options overflow on small devices and  Hide wiki-options dropdown for guest users

- wiki/public/js/editor.js
- wiki/public/js/render_wiki.js
- wiki/wiki/doctype/wiki_page/templates/editor.html
- wiki/wiki/doctype/wiki_page/wiki_page.py
If I accidentally close my tab or switch a page from the sidebar, I lose my edits. Now editor drafts will be stored in local storage:
https://github.com/user-attachments/assets/e17157e8-b612-42a2-abb0-2a7b23cfa2a0
- A new wiki page is stored locally even if no draft is created.
- If you have multiple wiki page drafts, edits for them are maintained separately.
- After opening edit mode for page/page draft, if a local draft is present, it will be loaded & the user is informed about this, else the document from the backend is shown
- Checks for outdated content if the Wiki Page is modified after the last local draft was saved
https://github.com/user-attachments/assets/aac39029-fd37-4573-bce8-53c66380b915
<hr>
**Why not continuously write to the Wiki Page Patch document instead of storing …
> feat: save editor drafts to localstorage
